language: node_js
node_js:
- 8.10.0
script: npm run cover
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - develop
notifications:
  email: false
  slack:
    template:
      - "%{repository_slug}"
      - "<%{build_url}|#%{build_number}> - %{message}"
      - "Commit: \"%{commit_subject}\" by %{author}"
    secure: eLYWTY7kUXDfvD1ZA7lBI5faY0zhPhczlpJkf82hkwtbw/wda5LpnpjKAa2cUMu0qk+F1PCMDEg8ctEVPwX18KmO+VyxwD7iOmL6husJgVfy+cnxgA+WDHGWXGjfl5lBuD5zq8A4fludNZW6aDi+csz8q8W/0hcjqOq4W5kuUVVksf1ZvSndcS3ptd4xakGU/RNlm/5NOuJZbzGEhKx80V/frdnrIPjdyKA1EWdetB/0L5WyxrNXyT5pftRtlmwYGZuyAkmda3RoAWL9LVfCb/Ec+4MMy8DdOuOn5Patdg9XqewLWIUSOKFStFnMsozlVeEvcXCsK+B4isTvDB0QzUWNXniH/I64zGwoIOFcypFHZ9piSK5dKhkCCJcujABn1jzPLqS/aiwnZy2Gf6EGiLbQFLgTxgKvK2BQ2Dooma6W7gjV3ddxg+Ocuh8kFaxRxaMt9l66WsGgFPaf/mg3u7KE+wHolSmUzGu9Cg0oDgUb4oJyuG8ulJaxK0Fku281ws3mnWH9c6rl99+ke0pY5WjZRQR5ofqfqnIfRFl4hnXB/C8XlwlWJBXpLGU6FyEv9QSk3venNPlwPkJrh9sKXXhtL1BOG6yGC6m/6hM09zi5MN2MlQkZ+h+cPOtdsKiH7TAIR0YRXdWUl7+l5vJwMRUaHaKr8fUt39s9y1QrsM4=
