language: node_js
node_js:
- 8.10.0
script: npm run cover
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - develop
notifications:
  email: false
  slack:
    template:
      - "%{repository_slug}"
      - "<%{build_url}|#%{build_number}> - %{message}"
      - "Commit: \"%{commit_subject}\" by %{author}"
    secure: fTbzcJKCFmsAiJn7UFKkXcSBl75WW3uY/oQyyHDotSCgR8v54wvwDM6DSMJiM2OF6z8Jab8T3B55V06YAkuE9BemK8toA3GnVygs3JFv2RmK/swnlGAfXJE6crC5uUWCZPnF9Iu29ZFof76VuHJmCZwK8zJyG+L+GXSSxXPOgmZ3BxKN+L3gc6eBVNLXGAQC4s+dAiNuRWg3XqxlVNBrI8/Tp/W6S8I6HPNABNkAQ3N8W7sodd7Zr7hDObHsz/LoaBBuKY8I/AxYK5i3itw51MA7hqQ3hbg5dh09g4hhHHQjcoPIYfn5Kto7wQnjRn52d6t61U62LVT/aAcrYldjYw0ov9u3cSkoqQVXcDPcKIJ79N4Vl24g9EqrJ+1sbM+bJn9RxzlXUWAYDyFGmm/TQJQkKnHUKwxB+y4LM1ckPqiIRJThQglCUSJWH1WM6d9+AkfGo2V+7w2CA21v7uDxPv3rRhw/KliRJsMT7LHNxKkP291Gq8aYdRuzCNSMWZfL0COM01xvinyxBiLzmQIkECmkGax1/eiiCaTe5XW95xIh0SYrv+sSI45pI3bVIkzMyIPtunWrdrJhpMKfH+uI5mz4ERgeSMaqiTKENAZUSy2+OLjV910tT271LRRj9T562rr7LHcxBKe7M4nsczntWGFTcOPzUkGt+FeXxWJmedM=
