language: node_js
node_js: node
script: NODE_ENV=production npm run coverage -- --maxWorkers=4
# Send coverage report to coveralls.io
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
  email: false
branches:
  only:
  - master
