install:
  - git clone --branch=${TRAVIS_BRANCH} https://github.com/shopgate/sdk-devserver.git ../../sdk-devserver
  - cd ../../sdk-devserver && npm install --update-binary
  - cd ../${TRAVIS_REPO_SLUG} && npm install --update-binary
  - ls ./extensions -l
  - node ../../sdk-devserver/extensions/setup.js
  - ls ./extensions
  - node ../../sdk-devserver/extensions/index.js
language: node_js
node_js:
  - "8.4.0"
script: "NODE_ENV=production npm run coverage -- --maxWorkers=4"
# Send coverage report to coveralls.io
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
notifications:
  slack:
    on_success: change
    on_failure: change
    secure: HXKi0l1hB+eRlwT0JrPsLNuhNL31U38FYKZbHOdQJ9MRIxoth6ryVtlfd1pj2bsn1S9KnzubRDJPAK4XrLX6yJpxgeMqEN0rpNx/ZxRAAGBIsGViPgFIVSLEdQAPF9/l0Y7KrhHj4/2w//l1IRUMNuueB/depwL1zuDl65LD2854fgO/+JKlKn6j/Y2CXA7aog57uzuZi9hSmgr4NR5J1fSTSa3eY/vuBgzdXYyRgjgvgzL5G2hHYB/4f7H1Gi0A5blFJItyL8LH10TeMT+r0HK+gvX8OSqmeX4GGSxWQoE0ud/z4Oe4wf/B3E/s8wXi1tWLDLMMoGUBYKW8qjRVKfRfSAlX4zC03sWVh6LT7oLqQzWgnFJOosU1FJVXlAEvnLrW+3TVnnqbiIzEkGPbHnMj/Ob6Z6Wx7IZIrRzrqp3cJl4aaIXTX+D5w36rSKzCbIBgnhd6UOpQ9h1w3IpKsBREDoERJWgf8mA1++lRTgurKsEtgTMuuudu5DlzoucQIj3Z2BFh19RUrO961uVy5opCaqtvLm8qWOK/mY3kfKThOe1N1xdY/0BJa2LgVuMkz7IxuRjXxVJydiZOdHh/tDz6XHw8MQ3th2j4iZ0p8UET/BWzyEKJQDH+getzj7Bju4gvpMHO1vHwIPXBByFBY2CVk7h0bEalO4Olg7FklVc=
  email: false
branches:
  only:
  - master
