language: node_js
node_js:
- 8.6.0
before_script: cd frontend/ && npm i
script: npm run cover -- --maxWorkers=4
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - develop
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}"
      - "<%{build_url}|#%{build_number}> - %{message}"
      - "Commit: \"%{commit_subject}\" by %{author}"
    secure: cLzn4uj06o5HQxfTVG0Mlg/Dq4YRJC+qNRpjsgDaTK2wtKFkkTZqRUaje/xrLDEncPXqw4UAoA1ua3CK1/Xy3NWWBox0cLB5gmelfJ1jhpOYwP3D7aQ6XVZB6pD0YwJow+wgGPAGAdO2XSJigUYvtXF2/ENP5d0xWQHIEoTVbLHr44tFk+cvf7ScOsEAFL3SHwugd0JUqSRCJMbJSTUtArmmhTZgRzmMgbkrIKKREQtv5UMAGou32blF3OasEJ8frQi+IPtRLGzqLzkE4LmemX2Q3IveyAt3WE21BJH+FqzhEXUTMzVts5SThElW1m9hSbd1KFMEE1gw/GatKCTux59rFWDZ/IEbi4JuWDTD76YEbih5WLuHkMU3aH9jaDu90hY9xGSIofQTwiSZT51p7N3pzBAWSbXCJH/HFhmtMB4m4dD4tRygPGWyn8QvGnCziTjzIkM83yYxzWaF1zmUVosHTGe2bayTFdiWEahU8aIhPbN6ZwmO+u07GGpDEpWizeKbhOx196jlbgARPx+q4SAodUKgOMn99P20BJb85X9mlCKGwHunCEJyqTGzF6XcqM+wnDog1iHrwPJNTyj1FG5oW0Tb+P4ZtdHBOVjt8RNj5COf6Z011ca83xZ7k6FHoq021rhsFUIlOL+Unk/9bHT6+DUrbdULvWdeu4PRG0E=
