language: node_js
node_js:
- 8.4.0
before_script: cd frontend/ && NODE_ENV=development npm i
script: NODE_ENV=production npm run cover -- --maxWorkers=4
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
  - develop
notifications:
  email: false
  slack:
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}"
      - "<%{build_url}|#%{build_number}> - %{message}"
      - "Commit: \"%{commit_subject}\" by %{author}"
    secure: HXzFdJiq7aE2m5ZuEbN3fgfHotiBJO2cdSP34TD69PDyDwFv1K3/MfcpYf40fYc0wivIjuPcuHO8+AbFT56YWtkI/yR1om19MRtN8O6+hmK/DREjV1mZEXk3jLaiAq+01wzvvF3DrDT+l++xewjp30bU1LFxISdgf5Hd1tfeJuj5YnLrm8CFuW80O8tr5acbF5m5Z5E+JAAg6npQ6r7wvikRdpZbmEsz7bI5emAyMovrexWK9HMpzOs6FE8zM/zUYz/SAE5k0Op18PFglyRAdLfu0Ns1bwiWbyydskkv+IMhok3hkVp7SGOue1lo7O8vwuK7NsrNRggI5AoWpy7+bODJGh9HmSMBC5fcBKyZeT/wbmlYK9BfTqklloXOARjbN/O5+gVp0xsSIob8y3Oh83pOgbxaszFV0Ltc9SU34owQXi+1AwSKqPutg2wJW1kIHB7sJmm3ZaBwJZ5wR4kUpI73CaczkZbHH6MxPoy2VkAtPZ7FJV9NIgmWO9cm7f7KyXHY2To2ca3D3dv2cNRlK1zB6DW2iDojGZWvLzAcjRgxIiDqTUN0xIzTLzWZVbp6UvbO4eORqgiwujyd2TtZsfZt0BZzpaD/iyf/vCB8o63s1cRMW7dK+vIGRjAD4ayxIgeua3NMv9yGFhteCn0x5e0I4zAXqwqxY8gRtmLiD7A=
